### DISCUSSION TITLE
Can I simply use 'Inter var' if I only need support for recent browsers?

### DISCUSSION THREAD

**Discussion by collimarco** [rsms/inter#584] [General]
I don't need support for legacy browsers, but only for recent ones.

Can I simply use `font-family: 'Inter var'` ?

What would be the browser support for that?

**Comment by rsms** [comment]
Yes! (You of course also need to import and declare the variable font files)

> What would be the browser support for that?

See https://caniuse.com/variable-fonts

**Reply by collimarco** [reply]
Thanks! On a modern browser that supports both, what is the advantage of using `font-family: 'Inter var'` instead of `font-family: 'Inter'`? Or the result is exactly the same?

**Reply by rsms** [reply]
No advantage; the browser will simply ignore the former.

Think of it this way: I'm at the grocery store and you text me "buy bananas" then I go to the fruit section and pick bananas, but before I check out from the store you text me again and say "buy oranges instead of bananas" so I put the bananas back and pick up oranges instead. What I pay for is the oranges.

Same thing with a lot of CSS stuff and fonts in particular in web browsers; only the final effective fonts are actually used. Same goes for loading font files — even if you declare 100 `@font-face` declarations with 100 different font files, only the actual font files needed are loaded. So when you use [`inter.css`](https://rsms.me/inter/inter.css) which has lots of `@font-face` declarations, you only pay for the fonts actually used, which in most cases means just loading a single font file (`Inter.var.woff2`)

Here's complete CSS for using [Inter version 4](https://github.com/rsms/inter/releases/tag/v4.0-beta9g) in "modern" web browsers:

```css
@font-face {
  font-family: "inter";
  font-weight: 100 900;
  font-display: swap;
  font-style: normal;
  src: url("res/Inter-Variable.woff2") format("woff2-variations"),
       url("res/Inter-Variable.woff2") format("woff2");
  src: url("res/Inter-Variable.woff2") format("woff2") tech("variations");
}
@font-face {
  font-family: "inter";
  font-weight: 100 900;
  font-display: swap;
  font-style: italic;
  src: url("res/Inter-Variable-Italic.woff2") format("woff2-variations"),
       url("res/Inter-Variable-Italic.woff2") format("woff2");
  src: url("res/Inter-Variable-Italic.woff2") format("woff2") tech("variations");
}
:root {
  font-family: inter, system-ui, sans-serif;
}
```
