### DISCUSSION TITLE
Provide fallback font metrics in css

### DISCUSSION THREAD

**Discussion by xPaw** [rsms/inter#632] [Ideas]
See https://developer.chrome.com/blog/font-fallbacks/

I used the following in v3, but properly authored metrics for v4 would be great to have.
```css
@font-face {
	font-family: fallback-inter;
	ascent-override: 90.20%;
	descent-override: 22.48%;
	line-gap-override: 0.00%;
	size-adjust: 107.40%;
	src: local("Arial");
}

body {
	font-family: Inter, fallback-inter;
}
```
