### DISCUSSION TITLE
Do I need to specify the same `font-feature-settings` again?

### DISCUSSION THREAD

**Discussion by KunalTanwar11** [rsms/inter#662] [Q&A] [answered]
Currently on the website it is mentioned that "If you're making a web thing, you can use the following HTML and CSS"

```css
:root {
  font-family: Inter, sans-serif;
  font-feature-settings: 'liga' 1, 'calt' 1; /* fix for Chrome */
}

@supports (font-variation-settings: normal) {
  :root {
    font-family: InterVariable, sans-serif;
  }
}
```

If I am using **Contextual Alternatives do I need to re-type** `'liga' 1, 'calt' 1` like this -

```css
@supports (font-variation-settings: normal) {
  :root {
    font-family: InterVariable, sans-serif;
    font-feature-settings: 'liga' 1, 'calt' 1, 'cv01', 'cv03', 'cv04', 'cv08', 'cv09', 'cv10';
  }
}
```

or only this `font-feature-settings: 'cv01', 'cv03', 'cv04', 'cv08', 'cv09', 'cv10';` is just fine?
