### ISSUE TITLE
Change default features

### ISSUE THREAD

**Issue by beojan** [rsms/inter#108]
Would it be possible to add some way to change the default set of enabled features, for use cases where it isn't possible to select these in the application (e.g. when setting Inter UI as the default desktop font)?

**Comment by rsms** [comment]
I'm not sure how much work it would be to allow this, but it would require on-the-fly font file compilation, which is complicated. Might be a lot of work, but I'm not sure. Would be great if someone could research this and viable approaches & solutions.

**Comment by beojan** [comment]
[Iosevka](https://github.com/be5invis/Iosevka) already has this, but the way that font is built is very different to Inter.

**Comment by jbergstroem** [comment]
I think one quick win here could be sub-setting by utf8 character ranges [similar to what google fonts does](https://developers.google.com/fonts/docs/getting_started#Subsets) since this is [also matched in CSS](https://caniuse.com/#feat=font-unicode-range), likely reducing the amount of bytes downloaded by the end user.

**Comment by rsms** [comment]
Subsetting is easy to do yourself.

Here's an example: (requires docker to be installed)

```
cat <<EOF | misc/vm --no-tty

pyftsubset build/fonts/const/Inter-UI-Regular.ttf \
  --unicodes=0000-0080 \
  --output-file=build/fonts/const/Inter-UI-Regular.basic_latin.ttf

woff2_compress build/fonts/const/Inter-UI-Regular.basic_latin.ttf

EOF
```

See `misc/vm pyftsubset --help` for detailed help.

**Comment by svenper** [comment]
There’s also [`pyftfeatfreeze`](https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze).

**Comment by VinSpee** [comment]
Hi! I ended up using https://github.com/filamentgroup/glyphhanger to subset, using the `--US_ASCII`, `--LATIN`, and a few other specific whitelist ranges, and was able to get the variable version down to ~100kb for upright and italic. Thanks!

**Comment by websocket98765** [comment]
Has anybody found settings to use on FontSquirel.com to get a subset of Inter Var successfully? I used "Basic Subsetting-Western languages" and the font is much smaller, but the "A" is messed up (it's not a solid color) and seems it may have lost its variable weight ability. https://www.fontsquirrel.com/tools/webfont-generator

Google Fonts doesn't seem to offer subsets either: https://fonts.google.com/specimen/Inter?query=inter#standard-styles

Hoping to find a GUI to easily get a subset.

**Comment by rsms** [comment]
> There’s also [`pyftfeatfreeze`](https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze).

Oh, [OpenType Feature Freezer](https://github.com/twardoch/fonttools-opentype-feature-freezer) is really neat. I often get the question of how to swap alternates.

**Comment by jasongitmail** [comment]
@rsms Just a thought, but you could automate creation of language-specific subsets using Github Actions. 

I wrote a Github Action to do this. You'd just need to add a script that generates the subsets when it is run called `build_subsets.py`.

1. Create a file `.github/workflows/subset.yml` .
2. Add the following:
```yml
name: Build subsets
on:
  push:
    branches: [master]
jobs:
  build_subsets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      # - run: python build_subsets.py # < Add subset script here
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

```
3. Add your `build_subsets.py` script to the repo, which generates the subsets.

Also, I did test this code to ensure the action works as expected. I built a demo [here](https://github.com/jasongitmail/actions-demo).

Happy to submit this as a PR, then you could push a commit containing the `build_subsets.py` script, if you'd like.

**Comment by rsms** [comment]
Neat idea @jasongitmail :-)

The `docs` folder in the Inter repo is "special" in that it is deployed by GitHub Pages to the official website and thus the font files in there must be synchronized with the current latest release on github (so that the website correctly reflect the fonts you may download and/or use via the CDN.)

There may not be an upside to using github actions for this. The async nature of GH action is an issue as well (the time it would take GH actions to complete its work is the duration of time when font files will be out of sync for users.)

An even better PR would be a subset script that can be run by the deploy script (or manually from a checkout) to generate subset font files!

**Comment by jasongitmail** [comment]
If it's just Github pages, I think we could make it work. 

Individual steps within a job run synchronously, so we can put a [Github Pages deploy step](https://github.com/marketplace/actions/github-pages-action) (see snippet below) as the last step after any other steps it depends on--like subset generation. Then change the repo's Github Pages branch to a _non-master_ branch (e.g. `gh-pages`) so that the website content & fonts only get deployed after everything works successfully. If any step fails (like the subset generation), then Github Actions bails and does not deploy.

The subset generation script would need to have a [return value to indicate success (`0`) or failure (non 0)](https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions).

```yml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
```

> An even better PR would be a subset script that can be run by the deploy script (or manually from a checkout) to generate subset font files!

I honestly know nothing about subsetting fonts. Just hoping to get an Inter Var English subset to save 100kb ;) But happy to help automate it!
