### ISSUE TITLE
Version number as comment in css file

### ISSUE THREAD

**Issue by pakastin** [rsms/inter#201]
Any change you could add version number as comment in CSS file? That would make it so much easier to serve static files with long cache time (I use just a single hash for all files, based on CSS file hash).

**Comment by rsms** [comment]
Is the version number (not hash) that’s currently in the CSS file not adequate? Can you help me understand how adding it to a comment would be different?

Excerpt from https://rsms.me/inter/inter.css:

```css
@font-face {
  font-family: 'Inter';
  font-style:  normal;
  font-weight: 100;
  font-display: swap;
  src: url("font-files/Inter-Thin.woff2?v=3.10") format("woff2"),
       url("font-files/Inter-Thin.woff?v=3.10") format("woff");
}
```
